// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKDHTWT-l8b4X7_4CvNlF3obFUO49hJY0',
    appId: '1:342048179657:web:b460e7a8dd10d452f91418',
    messagingSenderId: '342048179657',
    projectId: 'loginsignupauth-1dc25',
    authDomain: 'loginsignupauth-1dc25.firebaseapp.com',
    storageBucket: 'loginsignupauth-1dc25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF3Pj4iPWdjm5Dd_lYIWxHiko_YCNzJ3M',
    appId: '1:342048179657:android:3550049d59b57058f91418',
    messagingSenderId: '342048179657',
    projectId: 'loginsignupauth-1dc25',
    storageBucket: 'loginsignupauth-1dc25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV-0FkWLqOeWfmJbyktKbK6jfhaCjBPlw',
    appId: '1:342048179657:ios:aa6d1f219160fd53f91418',
    messagingSenderId: '342048179657',
    projectId: 'loginsignupauth-1dc25',
    storageBucket: 'loginsignupauth-1dc25.appspot.com',
    androidClientId: '342048179657-ihg38ujl51ktiu4e16vohhu2oijgs5od.apps.googleusercontent.com',
    iosClientId: '342048179657-o5q1iu97529m0sutrlmn23khpooehbea.apps.googleusercontent.com',
    iosBundleId: 'com.exam',
  );
}
